// const races = [
  //   { name: "Random", value: "Random" },
  //   { name: "Aasimar", value: "Aasimar" },
  //   { name: "Deep Gnome", value: "Deep Gnome" },
  //   { name: "Dragonborn", value: "Dragonborn" },
  //   { name: "Duergar", value: "Duergar" },
  //   { name: "Drow", value: "Drow" },
  //   { name: "Firbolg", value: "Firbolg" },
  //   { name: "Genasi", value: "Genasi" },
  //   { name: "Gnome", value: "Gnome" },
  //   { name: "Golbin", value: "Goblin" },
  //   { name: "Goliath", value: "Goliath" },
  //   { name: "Half-Elf", value: "Half-Elf" },
  //   { name: "Half-Orc", value: "Half-Orc" },
  //   { name: "High Elf", value: "High Elf" },
  //   { name: "Hill Dwarf", value: "Hill Dwarf" },
  //   { name: "Hobgoblin ", value: "Stout Halfling" },
  //   { name: "Human", value: "Human" },
  //   { name: "Kenku", value: "Kenku" },
  //   { name: "Kobold", value: "Kobold" },
  //   { name: "Lightfoot Halfling", value: "Lightfoot Halfling" },
  //   { name: "Lizardfolk", value: "Lizardfolk" },
  //   { name: "Mountain Dwarf", value: "Mountain Dwarf" },
  //   { name: "Orc", value: "Orc" },
  //   { name: "Tabaxi", value: "Tabaxi" },
  //   { name: "Tiefling", value: "Tiefling" },
  //   { name: "Triton", value: "Triton" },
  //   { name: "Stout Halfling", value: "Stout Halfling" },
  //   { name: "Wood Elf", value: "Wood Elf" },
  //   { name: "Yuan-Ti", value: "Yuan-Ti" },
  // ];

  // const sexes = [
  //   { name: "Random", value: "Random" },
  //   { name: "Male", value: "Male" },
  //   { name: "Female", value: "Female" },
  // ];

  // const aligns = [
  //   { name: "Random", value: "Random" },
  //   { name: "Lawful Good", value: "Lawful Good" },
  //   { name: "Neutral Good", value: "Neutral Good" },
  //   { name: "Chaotic Good", value: "Chaotic Good" },
  //   { name: "Lawful Neutral", value: "Lawful Good" },
  //   { name: "True Neutral", value: "True Neutral" },
  //   { name: "Chaotic Neutral", value: "Chaotic Neuutral" },
  //   { name: "Lawful Evil", value: "Lawful Evil" },
  //   { name: "Neutral Evil", value: "Neutral Evil" },
  //   { name: "Chaotic Evil", value: "Chaotic Evil" },
  // ];

  // const professions = [
  //   { name: "Animal Handler", value: "Animal Handler" },
  //   { name: "Arborist", value: "Arborist" },
  //   { name: "Architect", value: "Architect" },
  //   { name: "Baler", value: "Baler" },
  //   { name: "Beekeeper", value: "Beekeeper" },
  //   { name: "Breeder", value: "Breeder" },
  //   { name: "Brewmaster", value: "Brewmaster" },
  //   { name: "Brickmaker", value: "Brickmaker" },
  //   { name: "Brickmason", value: "Brickmason" },
  //   { name: "Carpenter", value: "Carpenter" },
  //   { name: "Construction Worker", value: "Construction Worker" },
  //   { name: "Cowherd", value: "Cowherd" },
  //   { name: "Dairyer", value: "Dairyer" },
  //   { name: "Falconer", value: "Falconer" },
  //   { name: "Farmer", value: "Farmer" },
  //   { name: "Fisher", value: "Fisher" },
  //   { name: "Florist", value: "Florist" },
  //   { name: "Forager", value: "Forager" },
  //   { name: "Forester", value: "Forester" },
  //   { name: "Fowler", value: "Fowler" },
  //   { name: "Gamekeeper", value: "Gamekeeper" },
  //   { name: "General Contractor", value: "General Contractor" },
  //   { name: "Glazier", value: "Glazier" },
  //   { name: "Groom", value: "Groom" },
  //   { name: "Herder", value: "Herder" },
  //   { name: "Horse Trainer", value: "Horse Trainer" },
  //   { name: "Hunter", value: "Hunter" },
  //   { name: "Jewler", value: "Jewler" },
  //   { name: "Lumberjack", value: "Lumberjack" },
  //   { name: "Master-of-Horses", value: "Master-of-Horses" },
  //   { name: "Master-of-Hounds", value: "Master-of-Hounds" },
  //   { name: "Miller", value: "Miller" },
  //   { name: "Miner", value: "Miner" },
  //   { name: "Pathfinder", value: "Pathfinder" },
  //   { name: "Plasterer", value: "Plasterer" },
  //   { name: "Plumer", value: "Plumer" },
  //   { name: "Prospector", value: "Prospector" },
  //   { name: "Ranger", value: "Ranger" },
  //   { name: "Renderer", value: "Renderer" },
  //   { name: "Roadlayer", value: "Roadlayer" },
  //   { name: "Roofer", value: "Roofer" },
  //   { name: "Shepard", value: "Shepard" },
  //   { name: "Stablehand", value: "Stablehand" },
  //   { name: "Thresher", value: "Thresher" },
  //   { name: "Trapper", value: "Trapper" },
  //   { name: "Vinter", value: "Vinter" },
  //   { name: "Smith", value: "Smith" },
  //   { name: "Stonemason", value: "Stonemason" },
  //   { name: "Zookeeper", value: "Zookeeper" },
  // ];

  // const features = [
  //   { name: "Random", value: "Random" },
  //   {
  //     name: "Distinctive jewelry: earrings, necklace, circlet, bracelets",
  //     value: "Distinctive jewelry: earrings, necklace, circlet, bracelets",
  //   },
  //   { name: "Piercings", value: "Piercings" },
  //   {
  //     name: "Flamboyant or outlandish clothes",
  //     value: "Flamboyant or outlandish clothes",
  //   },
  //   { name: "Formal, clean clothes", value: "Formal, clean clothes" },
  //   { name: "Ragged, dirty clothes", value: "Ragged, dirty clothes" },
  //   { name: "Pronounced scar", value: "Pronounced scar" },
  //   { name: "Missing teeth", value: "Missing teeth" },
  //   { name: "Missing fingers", value: "Missing fingers" },
  //   {
  //     name: "Unusual eye color (or two different colors)",
  //     value: "Unusual eye color (or two different colors)",
  //   },
  //   { name: "Tattoos", value: "Tattoos" },
  //   { name: "Birthmark", value: "Birthmark" },
  //   { name: "Unusual skin color", value: "Unusual skin color" },
  //   { name: "Bald", value: "Bald" },
  //   { name: "Braided beard or hair", value: "Braided beard or hair" },
  //   { name: "Unusual hair color", value: "Unusual hair color" },
  //   { name: "Nervous eye twitch", value: "Nervous eye twitch" },
  //   { name: "Distinctive nose", value: "Distinctive nose" },
  //   {
  //     name: "Distinctive posture (crooked or rigid)",
  //     value: "Distinctive posture (crooked or rigid)",
  //   },
  //   { name: "Exceptionally beautiful", value: "Exceptionally beautiful" },
  //   { name: "Exceptionally ugly", value: "Exceptionally ugly" },
  // ];

  // const abilities = [
  //   { name: "Strength", value: "Strength" },
  //   { name: "Dexterity", value: "Dexterity" },
  //   { name: "Constitution", value: "Constitution" },
  //   { name: "Intelligence ", value: "Intelligence" },
  //   { name: "Wisdom", value: "Wisdom" },
  //   { name: "Charisma", value: "Charisma" },
  // ];

  // const talents = [
  //   { name: "Plays a musical instrument", value: "Plays a musical instrument" },
  //   {
  //     name: "Speaks several languages fluently",
  //     value: "Speaks several languages fluently",
  //   },
  //   { name: "Unbelievably lucky", value: "Unbelievably lucky" },
  //   { name: "Perfect memory", value: "Perfect memory" },
  //   { name: "Great with animals", value: "Great with animals" },
  //   { name: "Great with children", value: "Great with children" },
  //   { name: "Great at solving puzzles", value: "Great at solving puzzles" },
  //   { name: "Great at one game", value: "Great at one game" },
  //   { name: "Great at impersonations", value: "Great at impersonations" },
  //   { name: "Draws beautifully", value: "Draws beautifully" },
  //   { name: "Paints beautifully", value: "Paints beautifully" },
  //   { name: "Sings beautifully", value: "Sings beautifully" },
  //   {
  //     name: "Drinks everyone under the table",
  //     value: "Drinks everyone under the table",
  //   },
  //   { name: "Expert carpenter", value: "Expert carpenter" },
  //   { name: "Expert cook", value: "Expert cook" },
  //   {
  //     name: "Expert dart thrower and rock skipper",
  //     value: "Expert dart thrower and rock skipper",
  //   },
  //   { name: "Expert juggler", value: "Expert juggler" },
  //   {
  //     name: "Skilled actor and master of disguise",
  //     value: "Skilled actor and master of disguise",
  //   },
  //   { name: "Skilled dancer", value: "Skilled dancer" },
  //   { name: "Knows thieves’ cant", value: "Knows thieves’ cant" },
  // ];

  // const mannerisms = [
  //   {
  //     name: "Prone to singing, whistling, or humming quietly",
  //     value: "Prone to singing, whistling, or humming quietly",
  //   },
  //   {
  //     name: "Speaks in rhyme or some other peculiar way",
  //     value: "Speaks in rhyme or some other peculiar way",
  //   },
  //   {
  //     name: "Particularly low or high voice",
  //     value: "Particularly low or high voice",
  //   },
  //   {
  //     name: "Speaks in an unusually formal manner",
  //     value: "Speaks in an unusually formal manner",
  //   },
  //   { name: "Enunciates overly clearly", value: "Enunciates overly clearly" },
  //   { name: "Speaker loudly", value: "Speaks Loudly" },
  //   { name: "Whispers", value: "Whispers" },
  //   {
  //     name: "Uses flowery speech or long words",
  //     value: "Uses flowery speech or long words",
  //   },
  //   {
  //     name: "Frequently uses the wrong word",
  //     value: "Frequently uses the wrong word",
  //   },
  //   {
  //     name: "Uses colorful oaths and exclamations",
  //     value: "Uses colorful oaths and exclamations",
  //   },
  //   {
  //     name: "Makes constant jokes or puns",
  //     value: "Makes constant jokes or puns",
  //   },
  //   {
  //     name: "Prone to predictions of doom",
  //     value: "Prone to predictions of doom",
  //   },
  //   { name: "Fidgets", value: "Fidgets" },
  //   { name: "Squints", value: "Squints" },
  //   { name: "Stares into the distance", value: "Stares into the distance" },
  //   { name: "Chews something", value: "Chews something" },
  //   { name: "Paces", value: "Paces" },
  //   { name: "Taps fingers", value: "Taps fingers" },
  //   { name: "Bites fingernails", value: "Bites fingernails" },
  //   { name: "Twirls hair or tugs beard", value: "Twirls hair or tugs beard" },
  // ];

  // const interactions = [
  //   { name: "Argumentative", value: "Argumentative" },
  //   { name: "Arrogant", value: "Arrogant" },
  //   { name: "Blustering", value: "Blustering" },
  //   { name: "Rude", value: "Rude" },
  //   { name: "Curious", value: "Curious" },
  //   { name: "Friendly", value: "Friendly" },
  //   { name: "Honest", value: "Honest" },
  //   { name: "Hot tempered", value: "Hot tempered" },
  //   { name: "Irritable", value: "Irritable" },
  //   { name: "Ponderous", value: "Ponderous" },
  //   { name: "Quiet", value: "Quiet" },
  //   { name: "Suspicious", value: "Suspicious" },
  // ];

  // const bonds = [
  //   {
  //     name: "Dedicated to fulfilling a personal life goal",
  //     value: "Dedicated to fulfilling a personal life goal",
  //   },
  //   {
  //     name: "Protective of close family members",
  //     value: "Protective of close family members",
  //   },
  //   {
  //     name: "Protective of colleagues or compatriots",
  //     value: "Protective of colleagues or compatriots",
  //   },
  //   {
  //     name: "Loyal to a benefactor, patron, or employer",
  //     value: "Loyal to a benefactor, patron, or employer",
  //   },
  //   {
  //     name: "Captivated by a romantic interest",
  //     value: "Captivated by a romantic interest",
  //   },
  //   { name: "Drawn to a special place", value: "Drawn to a special place" },
  //   {
  //     name: "Protective of a sentimental keepsake",
  //     value: "Protective of a sentimental keepsake",
  //   },
  //   {
  //     name: "Protective of a valuable possession",
  //     value: "Protective of a valuable possession",
  //   },
  //   { name: "Out for revenge", value: "Out for revenge" },
  // ];