<CustomDataTable
                tableName={"itemTypes"}
                setSingular={setWeakness}
                setPlural={setWeaknesss}
                setOptions={setWeaknessOptions}
                h1Title={"Weakness"}
                dialogHeader={"Weakness"}
                selectedWeakness={selectedWeakness}
                setSelectedWeakness={setSelectedWeakness}
                list={WeaknessList}
                setList={setWeaknessList}
                valueOptions={WeaknessOptions}
              />